### ISSUE TITLE
More specific exception reporting, esp. when the problem is the delimiter?

### ISSUE THREAD

**Issue by Eumaeus** [cite-architecture/scm#8] opened 2017-04-12 23:34 UTC
This will be the most common kind of error, I think, and it would be worth doing a little peeking, in the case of an exception, to see if we can be more informative in reporting the exception.

**Comment by neelsmith** [comment] 2017-04-14 21:16
Can you give me an example of a current exception report that needs to be improved?

**Comment by neelsmith** [comment] 2017-04-16 09:28
Possibly most helpful spot would be in ohco2's corpus constructor.  I bet that's where the rubber is really hitting the road.

**Comment by neelsmith** [comment] 2017-05-19 20:41
For scm, planning to work on this only when specific cases are logged here, since the odds are otherwise high that the issue is in a dependency.

**Comment by neelsmith** [comment] 2017-05-27 14:06
Closing for now.  Specific issues can be opened when users find messages that are too vague.

**Closed as completed by neelsmith** 2017-05-27 14:06 UTC
Labels: enhancement
